### PR TITLE
Add multiple pages support

### PR DESCRIPTION
**Pull request by danielnaab**
Initial work on #26

### CODE REVIEW

**Review by natashapl — COMMENTED** [review]
Hi Dan. Since I added this class name to these components, I feel compelled to ask... Why is the "edit-component-panel" class name being removed?

**Review by natashapl — COMMENTED** [review]
Hi Dan. Just wondering, why is the global nav styles being removed?

**Review by ethangardner — COMMENTED** [review]
Nothing jumps out at me as an issue, and a lot of what I see is a good evolution of the product and ongoing structure. This is a large pull request as you mentioned in Slack, so if there is a specific area that you want a little extra constructive scrutiny, let me know and I'm happy to do that. Otherwise, you should be ok to merge from my perspective.

**Comment by ethangardner** [comment]
Reviewed additional changes. LGTM.

**Comment by danielnaab** [comment]
Thanks @ethangardner. Merging now, to avoid merge conflicts, but @natashapl I'll touch base will you ASAP.

**Pull request merged**
